name: FunCommands
main: chibill.FunCommands.Main
version: 2.0.3
author: Chibill
commands:
  funversion:
    description: Gets the version of FunCommands
    usage: /<command>
    permission: FunCommands.version
    permission-message: You don't have permission!
  derps:
    description: List all the possible derps.
    usage: /<command>
    permission: FunCommands.derp
    permission-message: You don't have permission!

  derp:
    description: Prints out a random derp.
    usage: /<command> 
    permission: FunCommands.derp
    permission-message: You don't have permission!
  foodfight:
    description: A polite mealtime activity
    usage: /<command> victim
    permission: FunCommands.foodfight
    permission-message: You don't have permission!  
  slap:
    description: Slappings!
    usage: /slap <Player> <Object>
    permission: FunCommands.slap
    permission-message: You don't have permission!  